baseURL = "//notmy.space/"
languageCode = "en"
defaultContentLanguage = "en"
title = "William Floyd"
theme = "KeepIt"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = "**/media/src"

paginate = 12
enableEmoji = true
googleAnalytics = "UA-63647911-2"
enableRobotsTXT = false
canonifyURLs = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    subtitle = "This is not MySpace, it's my space"
    since = 2018
    author = "William Floyd"
    home_mode = ""

[params.gravatar]
    email = "william.png2000@gmail.com"

[params.social]
    GitHub = "W-Floyd"
    Linkedin = "william-floyd"
    Email   = "william.png2000@gmail.com"
    Steam = "W-Floyd"

[params.share]

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true