baseURL = "//notmy.space/"
languageCode = "en"
defaultContentLanguage = "en"
title = "William Floyd"
theme = "github.com/W-Floyd/hugo-coder-iconify"

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = "**/media/src"
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/mdi'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/simple-icons'

paginate = 20

pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

enableEmoji = true

[permalinks]
  posts = "/:year/:month/:filename/"

[params]
author = "William Floyd"
description = "William Floyd's personal website"
gravatar = "william.png2000@gmail.com"
dateFormat = "January 2, 2006"
since = 2018
colorScheme = "auto"

# If you want to implement a Content-Security-Policy, add this section
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "github"
weight = 1
url = "https://github.com/W-Floyd/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
weight = 2
url = "https://www.linkedin.com/in/william-floyd/"

[[params.social]]
name = "Email"
icon = "email"
weight = 3
url = "mailto:contact@notmy.space"

[[params.social]]
name = "SimpleX"
icon = "simplex"
iconVendor = "simple-icons"
weight = 4
url = "https://smp15.simplex.im/a#WKrWvI-cu2LK9RDYrnIK1a8F8zeEGMoKzTCuwTl2kuM"

[[params.social]]
name = "RSS"
icon = "rss"
weight = 5
url = "https://notmy.space/posts/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Resume"
weight = 2
url = "https://github.com/W-Floyd/misc-job/releases/download/release/William_Floyd.pdf"

[[languages.en.menu.main]]
name = "Posts"
weight = 3
url = "posts/"
