baseURL = "//notmy.space/blog/"
languageCode = "en"
defaultContentLanguage = "en"
title = "William Floyd's Blog"
theme = "KeepIt"
paginate = 10
canonifyURLs = true
enableEmoji = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    description = ""
    since = 2018
    author = "William Floyd"
    home_mode = "post"

[params.share]
